### ISSUE TITLE
I get question marks instead of letters

### ISSUE THREAD

**Issue by OctoOsmo** [benbarkay/htmltopdf-java#26]
When I use console tool (wkhtmltopdf 0.12.2.4) I have properly generated pdf.
But if I use this library I have question marks instead of letters.

This issue relevant for Ubuntu 16.04.5 LTS in docker.
On my windows 10 machine all working good.

**Comment by benbarkay** [comment]
Make sure that you have the relevant fonts and encodings installed in your
docker container.

**Comment by OctoOsmo** [comment]
But console whhtmltopdf works great. How could it work if I do not have fonts in system?
here is my font from html document:
style="font-size:14;font-family:times;text-align:left;border:solid 0px"
html document in utf-8 encoding.
Which font I should install?
