### ISSUE TITLE
在windows运行正常，在linux运行不起来

### ISSUE THREAD

**Issue by linxuebo** [benbarkay/htmltopdf-java#51]
请问引入mave依赖后，打成jar部署到linux还需要 在linux服务器上安装libwkhtmltox插件吗？我没安装插件，在linux上运行就报“Unable to load library '/tmp/io.woo.htmltopdf/wkhtmltox/0.12.5/libwkhtmltox.so'”这样的错误

**Comment by xuanjinnan** [comment]
我也一样，这就是个坑
